baseURL = "https://samadesoga.me/"
languageCode = "en-us"
enableRobotsTXT = true
canonifyURLs = true
title = "Sam Adesoga's Personal Blog"
theme = "blogezy"
disqusShortname = "samblog-a664e-firebaseapp-com"
googleAnalytics = "G-PL5WFD5XRN"

# Nav links in the side bar
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Agile Delivery"
url = "categories/agile-delivery"
weight = 2

[[menu.main]]
name = "Agile Coaching"
url = "categories/coaching"
weight = 2

[[menu.main]]
name = "Technical"
url = "categories/technical"
weight = 3

[[menu.main]]
name = "Feature"
url = "categories/feature"
weight = 4

[[menu.main]]
name = "About"
url = "about"
weight = 5

[[menu.main]]
name = "Contact"
url = "contact"
weight = 6

[params]
  author = "Samuel Adesoga"
  email = "samuel@valuehut.co"
  env = "production"
  description = "Enterprise Agility, Leadership, Innovation and Personal Development"
  tagline = "Agile Management Consultant"
  twitter = "@sadesoga"
  CanonifyUrls = "true"
  includeReadingTime = true

[params.social]
facebook      = "https://www.facebook.com/mistar.adesoga"
email         = "samuel@valuehut.co"
twitter       = "https://x.com/sadesoga"
linkedin      = "https://uk.linkedin.com/in/samueladesoga"
instagram     = "https://www.instagram.com/sam_adesoga/"
github        = "https://github.com/samueladesoga"