baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sam Adesoga's Personal Blog"
theme = "blogezy"

# Nav links in the side bar
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Feature"
url = "categories/feature"
weight = 2

[[menu.main]]
name = "Technology"
url = "categories/technology"
weight = 3


[[menu.main]]
name = "About"
url = "about/"
weight = 4

[[menu.main]]
name = "Get in touch"
url = "contact/"
weight = 5

[params.social]
facebook      = "https://www.facebook.com/mistar.adesoga"
email         = "samuel@thoughtstudiosng.com"
twitter       = "https://twitter.com/sadesoga"
linkedin      = "https://uk.linkedin.com/in/samueladesoga"
instagram     = "https://www.instagram.com/mistaradesoga/"
github        = "https://github.com/samueladesoga"