on: [push]
name: Publish blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: samueladesoga/github-action-hugo-deploy-to-firebase@master
      with:
        firebase-token: ${{ secrets.secret_firebase_token }}
        alias: ${{ some_alias }} // OPTIONAL
